### ISSUE TITLE
Décalage horaire pour les tracks

### ISSUE THREAD

**Issue by Benbb96** [Benbb96/benbb96-website#46]
L'heure récupéré par Panda est celle du serveur, cela devrait être l'heure avec le décalage horaire pour rester cohérent.

**Comment by J-Merle** [comment]
Je pense qu'il faudrait passer de : 
`df['datetime'] = pd.to_datetime(df['datetime'])` 
à quelque chose comme 
`df['datetime'] = pd.to_datetime(df['datetime']).tz_convert('Europe/Paris')` .

Tu dois aussi appeler avant `tz_localize()` pour définir le timezone de base de la date et que la conversion se fasse vraiement correctement.

On aurait alors quelque chose comme 
`df['datetime']= pd.to_datetime(df['datetime']).tz_localize('XXXXX').tz_convert('Europe/Paris')` 

[Doc `tz_localize()`](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.tz_localize.html)
[Doc `tz_convert()`](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.tz_convert.html)

**Comment by Benbb96** [comment]
Thanks @J-Merle  !
Yavait pas besoin de `tz_localise` car mes dates sont déjà awares dans Django mais tu m'as fait gagner du temps pour le `tz_convert`. C'est sympa d'être passé par ici :smile:
